# Change these first
owner: software-architects # Your GitHub organization or username, where this repository lives
repo: timecockpit-status # The name of this repository

sites:
  - name: Web Client
    url: https://web.timecockpit.com/version
    slug: web
    type: globalping
    location: Austria
    maxResponseTime: 15000
    expectedStatusCodes:
      - 200
  - name: API
    url: https://api.timecockpit.com/version
    slug: api
    type: globalping
    location: Austria
    maxResponseTime: 30000
    expectedStatusCodes:
      - 200
  - name: Identity Server
    url: https://auth.timecockpit.com/health
    # TODO review this vs. oidc
    slug: auth
    type: globalping
    location: Austria
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
  - name: Management Service
    url: https://management.timecockpit.com/health
    slug: mgmt
    type: globalping
    location: Austria
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
  - name: Website
    url: https://www.timecockpit.com
    slug: www
    type: globalping
    location: Austria
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200

workflowSchedule:
#  graphs: "0 0 * * *"
#  responseTime: "0 23 * * *"
#  staticSite: "0 1 * * *"
#  summary: "0 0 * * *"
#  updateTemplate: "0 0 * * *"
#  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.timecockpit.com
  # baseUrl: /your-repo-name
  logoUrl: https://statictimecockpit.blob.core.windows.net/logos/timecockpit.svg
  favicon: https://example.com/favicon.png
  faviconSvg: https://example.com/logo.svg
  name: time cockpit
  hideNavTitle: true
  introTitle: "**time cockpit** - Effortless Time Tracking for Projects and Work Hours"
  introMessage: Current status of time cockpit operations.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://www.timecockpit.com
    - title: Webclient
      href: https://web.timecockpit.com
    - title: Docs
      href: https://docs.timecockpit.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees: # Users to assign downtime issues (optional)
  - sopelt

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
